### ISSUE TITLE
Library isn't compatible with @tanstack/svelte-query v5

### ISSUE THREAD

**Issue by yinkakun** [vishalbalaji/trpc-svelte-query-adapter#14]
I was having error while trying to use this library with @tanstack/svelte-query v5.

This library imports some stuff that aren't available in the @tanstack/svelte-query v5. Specifically:`ResetQueryFilters` and `CreateQueriesResult`

**Comment by vishalbalaji** [comment]
Hi @yinkakun, thank you for pointing this out to me! Sorry for the late response, been a little busy with my day job. These issues have now been addressed in `v2.2.0`.

**Comment by vishalbalaji** [comment]
Closing this issue, Resolved in aab3bb056e276dc552a1742fe1667e8481b107da.
