### ISSUE TITLE
The `trpc: { abortOnUnmount: boolean }` type is now (unintentionally?) required on every query

### ISSUE THREAD

**Issue by fnimick** [vishalbalaji/trpc-svelte-query-adapter#19]
This happens due to `TRPCQueryOpts` now being required on `createQuery`: https://github.com/vishalbalaji/trpc-svelte-query-adapter/blob/481aa9bb894542980c4101a0dbbeb71295f7b111/src/index.ts#L207

Based on my cursor read, this isn't required since all lookups are of `opts?.trpc?.abortOnUnmount` - implying that null values are valid here. Should the type be changed?

**Comment by vishalbalaji** [comment]
You are absolutely right, both `trpc` and `abortOnUnmount` should be optional. Thanks a lot for pointing this out!
