### ISSUE TITLE
Publish to npm or contribute the source code to trpc-sveltekit

### ISSUE THREAD

**Issue by icflorescu** [vishalbalaji/trpc-svelte-query-adapter#2]
Outstanding work, @vishalbalaji! Looks great!

Would you be interested in publishing your package to `npm` or contributing this source code to [`trpc-sveltekit`](https://github.com/icflorescu/trpc-sveltekit)?

**Comment by vishalbalaji** [comment]
(Duplicate comment from [here](https://github.com/icflorescu/trpc-sveltekit/issues/53#issuecomment-1407712594), re-posted for consistency.)

@icflorescu I intend to put it up on `npm` once it reaches MVP, which is still a few features away(see #1). I am working towards it right now and I'll update the README here as soon as I do that. In the meantime, if anybody wishes to test out the package and report any glaring issues, I would really appreciate it.

Closing this issue for now.
