### ISSUE TITLE
Type error when using getQueryKey

### ISSUE THREAD

**Issue by smaven** [vishalbalaji/trpc-svelte-query-adapter#35]
I have the following procedure:
```typescript
export const userRouter = {
  all: publicProcedure
    .input(
      z
        .object({
          name: z.string(),
        })
        .optional(),
    )
    .query(async ({ input }) => {
      return 'something'
    }),
} satisfies TRPCRouterRecord;
```
Trying to get the query key gives me the following type error:
<img width="1295" alt="image" src="https://github.com/vishalbalaji/trpc-svelte-query-adapter/assets/36948032/4d0ca84f-514d-4b80-84a8-e8ca69de78e6">

Seems like the `type GetQueryKey` is not accounting for the `void` type
```typescript
type GetQueryKey<TInput = undefined> = TInput extends undefined
	? {
		[ProcedureNames.queryKey]: () => QueryKey
	}
	: {
		/**
		 * Method to extract the query key for a procedure
		 * @param type - defaults to `any`
		 */
		[ProcedureNames.queryKey]: (input: TInput, type?: QueryType) => QueryKey
	} & {}
```
This can be fixed by modifying the type as:
```typescript
type GetQueryKey<TInput = undefined> = [TInput] extends [undefined] | [void]
	? {
		[ProcedureNames.queryKey]: () => QueryKey
	}
	: {
		/**
		 * Method to extract the query key for a procedure
		 * @param type - defaults to `any`
		 */
		[ProcedureNames.queryKey]: (input: TInput, type?: QueryType) => QueryKey
	} & {}
```
If it looks good, I'll be happy to create a PR for this fix.

P.S. Great work on this package! 🙌

**Comment by vishalbalaji** [comment]
Hey @smaven thanks for letting me know! I suppose `[TInput] extends [undefined] | [void]` could be re-written as `[TInput] extends [undefined | void]`. Other than that, I would be happy to merge this PR if you were to raise one.
