### ISSUE TITLE
Variables/Data are not send on mutations

### ISSUE THREAD

**Issue by sharmapukar217** [vishalbalaji/trpc-svelte-query-adapter#4]
Seems like the variables are not sent while using useMutation(), I am not sure if those are send on useQuery() or not but for useMutation(), no data is sent back to server

**Comment by vishalbalaji** [comment]
Hi, could you please provide your router and how you were calling the method so that I can try and recreate it?

**Comment by vishalbalaji** [comment]
I noticed that I was not actually passing the input to the `useMutation().mutate` function to the `trpc` mutation. Please check if `v1.0.9` fixes it and let me know.
