### ISSUE TITLE
query and createQuery at same instance

### ISSUE THREAD

**Issue by plckr** [vishalbalaji/trpc-svelte-query-adapter#56]
I just stumbled upon this package because I need to integrate svelte-query with trpc, so far I was doing it by hand.

One thing that I was expecting was to have the `svelteQueryWrapper` instance to be able to both `createQuery` but also query directly.

Example of what I mean:
```ts
import { trpc } from '$lib/trpc';

const data = trpc($page).hello.query();

const query = trpc($page).hello.createQuery();
```

Based on this, what's the intended way to do it? Should I have two different instances to accomplish it? Or is there any planned changes to support this?

**Comment by vishalbalaji** [comment]
Hey @plckr, you can get access to the original client via the `createUtils` helper, like mentioned here: https://trpc.io/docs/client/react/useUtils#proxy-client

For your use case, you might want to do something like so:
```typescript
import { trpc } from '$lib/trpc';

const api = trpc($page)
const utils = api.createUtils()
const data = utils.client.hello.query()
```

**Comment by plckr** [comment]
thank you for the fast response!
I don't like much that boilerplate to have the original client, but it helps to know that. 
I'll try to simplify it through an helper function

**Comment by vishalbalaji** [comment]
@plckr Forgot to mention this in my original comment, but another option would be to simply also export your original trpc client separately and import that wherever you need it. Might be simpler than using `createUtils` to get it...
