### ISSUE TITLE
Infinite queries? 

### ISSUE THREAD

**Issue by qudo-code** [vishalbalaji/trpc-svelte-query-adapter#9]
Hello, is it possible to to this pattern with this package? It seems like all input to `trpcWithQuery` goes to the endpoint and not to setup the query as seen here.
![Screenshot 2023-03-09 at 7 57 47 PM](https://user-images.githubusercontent.com/59782726/224219871-404b0ae1-dafd-4716-9611-1226440a4329.png)

**Comment by qudo-code** [comment]
https://tanstack.com/query/latest/docs/svelte/examples/svelte/load-more-infinite-scroll

**Comment by qudo-code** [comment]
![Screenshot 2023-03-09 at 8 12 11 PM](https://user-images.githubusercontent.com/59782726/224221517-0abaea2d-b717-441c-8e21-4c766940d1d3.png)
![Screenshot 2023-03-09 at 8 12 26 PM](https://user-images.githubusercontent.com/59782726/224221534-d5166f9c-cca1-4ab7-b251-8ade4069d647.png)

Notice I can `createQuery` but not `createInfiniteQuery`.

**Comment by vishalbalaji** [comment]
It is possible to do so. According to https://trpc.io/docs/useInfiniteQuery, your procedure would need to take in an optional param called `cursor`, which should show you `createInfiniteQuery` in your autocomplete.

I am assuming that this is the issue. If not, could you please share what the procedure looks like in the router for me to look into?

**Comment by qudo-code** [comment]
Yeah, I am assuming this is the issue as well, feel free to close this. Thanks for that.

**Comment by vishalbalaji** [comment]
Okay then, closing.
